# Generated by Django 4.2.20 on 2025-04-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('dynasty', models.CharField(max_length=50, verbose_name='朝代')),
                ('content', models.TextField(verbose_name='内容')),
                ('translation', models.TextField(verbose_name='翻译')),
                ('type', models.CharField(choices=[('poetry', '古诗'), ('prose', '古文')], max_length=10, verbose_name='内容类型')),
                ('cover_image', models.CharField(max_length=255, verbose_name='封面图片路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('video_url', models.CharField(max_length=255, verbose_name='视频URL')),
            ],
            options={
                'verbose_name': '古诗',
                'verbose_name_plural': '古诗',
            },
        ),
        migrations.CreateModel(
            name='Prose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('dynasty', models.CharField(max_length=50, verbose_name='朝代')),
                ('content', models.TextField(verbose_name='内容')),
                ('translation', models.TextField(verbose_name='翻译')),
                ('type', models.CharField(choices=[('poetry', '古诗'), ('prose', '古文')], max_length=10, verbose_name='内容类型')),
                ('cover_image', models.CharField(max_length=255, verbose_name='封面图片路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('video_url', models.CharField(max_length=255, verbose_name='视频URL')),
                ('annotation', models.JSONField(blank=True, default=list, verbose_name='注释')),
                ('appreciation', models.TextField(blank=True, verbose_name='赏析')),
            ],
            options={
                'verbose_name': '古文',
                'verbose_name_plural': '古文',
            },
        ),
    ]
